### ISSUE TITLE
Use `sh -e` everywhere to notice errors in startup commands

### ISSUE THREAD

**Issue by sttts** [kcp-dev/helm-charts#7]
Today we have `sh -c "script"` which hides errors.

**Comment by xrstf** [comment]
The `virtual-workspaces` sidecar container has since been removed, as virtual workspaces run in-process in the kcp process. [This](https://github.com/kcp-dev/helm-charts/blob/6265d9a7d66431977fbf651d1041a62cd2814880/charts/kcp/templates/kcp.yaml#L297-L299) was supposedly the only place where we used `sh -c`.
